<a href="https://colab.research.google.com/github/IqraRehman/piaic_q2_Assignments/blob/master/Assignment_2(Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones((2,5),dtype=np.int32)
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [ ]:
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [ ]:
arr = np.arange(15)
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [ ]:
arrsq = np.arange(25).reshape(5,5)
np.square(arrsq)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
arr = np.arange(30).reshape(5,6)
print(arr)
print("##################")
print("Mean of array is: ",arr.mean())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
##################
Mean of array is:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [ ]:
arr.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [ ]:
np.median(arr)


14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [ ]:
arr.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [ ]:
arr4 = np.arange(16).reshape(4,4)
arr4.trace()

30

## Question:13

### Find the determinant of the previous array in Q12?

In [ ]:
from numpy.linalg import *
det(arr4)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [ ]:
arr = np.arange(10)
print("5th percentile of array is: ",np.percentile(arr,5))#5th percentile = 9*5% = 9*0.05 = 4.95
print("95th percentile of array is: ",np.percentile(arr,95))#9*95% = 9*0.95 = 8.55

5th percentile of array is:  0.45
95th percentile of array is:  8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,np.NaN])
np.isnan(arr)

array([False, False, False, False, False,  True])