<a href="https://colab.research.google.com/github/IqraRehman/piaic_q2_Assignments/blob/master/Assignment_1(Numpy_Fundamentals).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
arrzero = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [ ]:
arr1 = np.arange(10,49)

4. Find the shape of previous array in question 3

In [ ]:
np.shape(arr1)

(39,)

5. Print the type of the previous array in question 3

In [ ]:
arr1.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [ ]:
pip --version numpy

pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)


7. Print the dimension of the array in question 3


In [ ]:
np.ndim(arr1)

1

8. Create a boolean array with all the True values

In [ ]:
barr1 = np.array([34,56,13,90])
barr2 = np.array([30,50,10,67])
barr1 > barr2

array([ True,  True,  True,  True])

9. Create a two dimensional array




In [ ]:
twod = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])


10. Create a three dimensional array



In [ ]:
threed = np.array([[[10,20,30,40,50],[12,34,123,7,4],[45,32,12,90,56]]])


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
revvec = twod.ravel()
revvec[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [ ]:
idenmat = np.identity(3)
idenmat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
arr = np.array([1, 2, 3, 4, 5],dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 < arr2
arr1 > arr2
arr1 == arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [ ]:
odd = np.arange(10)
oddarr = odd[1:10:2]
oddarr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [ ]:
odd[oddarr] = -1
odd

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
x = np.ones((5,5))
x[1:4,1:4] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[[0,0]] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
arr2d = np.arange(10).reshape(2,5)
arr2d[:1]

array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
arr2d[1:]

array([[5, 6, 7, 8, 9]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
arr2d[0:,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr_rand = np.array(np.random.rand(10,10))
print(f'Minimum value of array is: {arr_rand.min()}')
print(f'Maximum value of array is: {arr_rand.max()}')

Minimum value of array is: 0.005820763281233821
Maximum value of array is: 0.9691047204796082


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names!='Will']

array([[ 0.26546518,  0.99260061,  0.3578313 , -0.86731004],
       [-0.46043737, -0.67874433, -0.26404468,  2.01120737],
       [ 0.34358603,  0.4511239 ,  0.00280108, -1.10401223],
       [ 0.27181265,  2.49308406,  2.37119767, -2.13625895],
       [-0.51025896,  0.98959894,  0.64824634,  1.53494618]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names!='Will') & (names!='Joe')]

array([[ 1.26812739, -1.04967157,  1.86991558,  0.079802  ],
       [-2.12787398, -1.52347263,  0.48133085,  0.97862515]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
arr_2d = np.array(np.random.randn(1,15)).reshape(5,3)
arr_2d.astype('float')

array([[-0.86649078,  1.783319  , -2.79975763],
       [ 0.2490323 , -0.34850154,  0.71774116],
       [ 1.01657252, -0.50642982,  1.68808591],
       [-0.54221509,  0.34474326, -1.06366872],
       [ 0.84034937,  1.06097792, -0.85184966]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
arr_2d = np.array(np.random.randn(1,16)).reshape(2,2,4)
arr_2d.astype(np.float)

array([[[-0.4177751 ,  1.30153606,  0.82762121, -1.26317353],
        [-0.20319783, -1.03467431, -0.63913155, -0.22058271]],

       [[ 1.35424097,  0.47799575,  1.23337055, -0.07170418],
        [-0.22645724, -0.20914397,  0.94618916,  2.68309281]]])

33. Swap axes of the array you created in Question 32

In [ ]:
arr_2d.T

array([[[-0.4177751 ,  1.35424097],
        [-0.20319783, -0.22645724]],

       [[ 1.30153606,  0.47799575],
        [-1.03467431, -0.20914397]],

       [[ 0.82762121,  1.23337055],
        [-0.63913155,  0.94618916]],

       [[-1.26317353, -0.07170418],
        [-0.22058271,  2.68309281]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
arr = np.array(np.random.rand(10))
arr[np.sqrt(arr) < 0.5] = 0
arr

array([0.28894274, 0.        , 0.48346922, 0.42467277, 0.49436145,
       0.        , 0.        , 0.84613917, 0.        , 0.93864521])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
np.maximum(arr1,arr2)

array([ 0.0694091 ,  0.74950504, -0.33017601,  1.01232138,  0.36554776,
       -0.47328131,  0.46983071,  1.61669457,  1.09179511, -0.06408838,
       -0.09029871, -0.75872418])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniquenames = np.unique(names)
np.sort(uniquenames,axis=-1,kind='stable')

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.intersect1d(a,b)
np.delete(a,4)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr =np.delete(sampleArray,1,0)
newColumn = np.array([[10,10,10]])
sampleArray[[1,0]] = newColumn
sampleArray

array([[10, 10, 10],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
arr = np.array(np.random.randn(4,5))
arr.cumsum()

array([-0.49473585, -2.3617076 , -2.38149436, -1.72781932, -2.10460604,
       -1.71042712, -2.6207182 , -1.28762319, -0.4955559 , -1.01254471,
       -2.2790303 , -1.89283915, -1.85050021, -0.32333077,  0.72969786,
        1.38768295,  1.57888431,  0.36462355, -2.16071184, -1.20072975])